### ISSUE TITLE
A few minor enhancement requests

### ISSUE THREAD

**Issue by vered1986** [acl2017/acl2017.github.io#36]
Thanks for the nice idea and implementation! A few minor enhancement requests:

* I think it would be easier if the time column applied to all the items in the table (e.g. also invited talks, lunch, etc). Currently there is only the time of the specific talks I selected.

* It might be easier to have a different formatting (color/bold/italic) to the room and topic of each item. 

* Perhaps coloring the line of the breaks in a different color? It's not crucial but might be more readable.

**Comment by desilinguist** [comment]
Thanks @vered1986 for taking the time to test this. I like all your suggestions and I think they should help in making the PDF easier to read. I will try and incorporate all of them.

**Comment by desilinguist** [comment]
Hi @vered1986 most of your suggestions are now incorporated. Can you please try testing again (please read the notes at the top since they have changed)? Thanks!

**Comment by keisks** [comment]
Hi Nitin (@desilinguist),

Thank you so much for your work on this. I really like it!
I have a couple of minor suggestions for the PDF. 

1.  It would be easier to read if the title and authors have different fonts (e.g., italic vs bold).
2. We might want author information for poster presentations, tutorials, invited talks as well. (This might be space consuming, though.) Currently, oral presentations have author information, but others don't. It would be nice if it's consistent.

**Comment by desilinguist** [comment]
Hi @keisks 

Thanks for taking the time! Yes, I'll add the authors for the tutorials. For the posters, I'm not so sure because I don't want the row to take too much space but I'll try it and see how it looks. 

As for your second suggestion, unfortunately, I can only apply a single style to the cell in the table PDF and that's it - can't apply multiple font styles. Sorry :/

**Comment by vered1986** [comment]
Hi @desilinguist, thanks, it looks great now!

**Comment by desilinguist** [comment]
Authors will now be included in the tutorial and poster rows in the PDF. Addressed by #51.
