### ISSUE TITLE
Tiny change

### ISSUE THREAD

**Issue by marziehf** [acl2017/acl2017.github.io#37]
Works fine on MacOS Chrome and Android Nougat. 
The only tiny change I suggest is to generate a more coherent file name for the program pdf (now it's download.pdf), especially since you cannot change the name on your phone (at least on mine), and someone might want to generate more than one program.

**Comment by desilinguist** [comment]
Thanks for taking the time to test and file an issue @marziehf! I had already tried to figure out how to do this but unfortunately given the way that the PDF is generated (via passing the PDF rendering data in base64-encoded format directly to the browser), I cannot set the name of the PDF.  The browser chooses some default name for the PDF on its own. I will try and look into this again but if I can't solve it, I will at least add a note about it to the page so people know how to deal with it.
