### ISSUE TITLE
Tutorials are not selectable

### ISSUE THREAD

**Issue by nschneid** [acl2017/acl2017.github.io#38]
I was expecting that in any time slot with multiple options, those options would be selectable.

(Firefox 52.0.2 on OS X)

**Comment by desilinguist** [comment]
Right. The testing notes do mention that.

I figured that you already know what tutorials you've paid for so I didn't
really consider that as something people would want but it's certainly
doable.

**Comment by desilinguist** [comment]
This is now supported.
