### ISSUE TITLE
Time slots are not vertically aligned across parallel sessions

### ISSUE THREAD

**Issue by nschneid** [acl2017/acl2017.github.io#39]
When expanding multiple parallel sessions, the length of each paper's title & author list determines how much vertical space it takes up. Thus, papers in the same time slot are not always vertically aligned, so the user has to do more work to see which papers are in competition. I can think of two workarounds:

1) Use a table for each set of parallel sessions, so it is forced to render each row with the same height across the parallel sessions. (This could get complicated if the parallel sessions subdivide their time differently, but I don't know if this ever happens in the main conference.)

2) Leave the vertical alignment as is but create a hover effect to indicate which papers are in the same slot. E.g., when I hover over the 12:20-12:30 paper in Knowledge Acquisition, the text in the parallel 12:20-12:30 papers is grayed out. And when I select it, the parallel papers stay grayed out.

(Desktop Firefox 52.0.2 on OS X)

**Comment by desilinguist** [comment]
Great suggestions. Thanks!

**Comment by desilinguist** [comment]
I have now implemented (2). Can you please try again (please read the testing notes again as they have changed. Thanks!

**Comment by ZeerakW** [comment]
Am just testing and (2) seems to be working (Safari 10.1 on OS X).

**Comment by nschneid** [comment]
Looks great! I like the ability to select multiple things in the same time slot and narrow it down later.
