### ISSUE TITLE
Calendar export?

### ISSUE THREAD

**Issue by nschneid** [acl2017/acl2017.github.io#41]
I realize this may be tricky to pull off, but *ideally* instead of a PDF, it would be convenient to export each paper (or chunk of papers in the same session) as a calendar entry. This way the schedule would get automatically synced with my phone (via Google Calendar), and this would also allow custom entries in between talks ("meet with so-and-so").

But the PDF option is certainly a step in the right direction. Thanks for making this happen!

**Comment by desilinguist** [comment]
Hmm, I know that there's a JS library to create `.ics` files but I think it would require a bit more work then I had anticipated. I'll see if I can find the time. 

In general, my thinking for the website program page was to generate something printable and rely on the (upcoming) conference app for providing an electronic, customizable schedule. The app will have a way to select items from the program and set reminders for them. Unfortunately, there is no way to export the information out of the app so it's not exactly what you want. May be next year :)

Thanks!

**Comment by desilinguist** [comment]
The JS library to create `.ics` files is really old and doesn't really seem to work so I don't think calendar exporting is on the cards for this year. Sorry :/
