### ISSUE TITLE
Expand all / collapse all buttons

### ISSUE THREAD

**Issue by danielhers** [acl2017/acl2017.github.io#44]
Related to #35, but rather than expanding all parallel sessions by default, there could be an 'expand all' button and a 'collapse all' button for all sessions.

**Comment by desilinguist** [comment]
Ah, and may be that button is only shown for larger screen devices just like the hovering, and not for mobile devices where the sessions are not adjacent. Good idea. I will see if I can incorporate this. Thanks!

**Comment by desilinguist** [comment]
This is now done by holding down the Shift-key and clicking - to expand/collapse all sessions.
