### ISSUE TITLE
Background colour for the room names

### ISSUE THREAD

**Issue by ZeerakW** [acl2017/acl2017.github.io#46]
## Environment information

- **Platform:** 
- **Operating system (incl. full version):** OS X Sierra 10.12.4
- **Browser (incl. version):** Safari 10.1
---

All of location designations shift background colour when you hover, which to me indicates that they're buttons, which they aren't. Just giving them a static background would be great. Alternatively it could be nice to have these colour coded if a presentation in the session is selected on the site & keep same colours in the PDF for easier and consistent navigation on the site and in the printout.

**Comment by desilinguist** [comment]
Yes, I agree about the location buttons not changing color when you hover on them. I will fix that.

I don't really want to use colors in the PDF since most people will be printing in black and white anyway.

**Comment by desilinguist** [comment]
Actually, perhaps I could link the location buttons to a pop-up window showing the floor plan in which case they can be left as actual buttons? This might actually be useful if you want to decide whether you can switch between one session and another.

**Comment by ZeerakW** [comment]
reg. PDF's that's a good point.

And opening a pop-up showing the floor plan would be extremely cool and helpful (it certainly would have been useful in Berlin).

**Comment by desilinguist** [comment]
Addressed with the floor-plan pop-up.
