### ISSUE TITLE
for tutorials, pease include the presenters and a link to the abstracts

### ISSUE THREAD

**Issue by aagohary** [acl2017/acl2017.github.io#48]
---

## Environment information

- **Platform:** 
- **Operating system (incl. full version): Ubuntu 16.10 
- **Browser (incl. version): Google chrome 

---

## Expected behavior

For the tutorials, it'd be good to show the names of the presenters and maybe a link to the abstract in the 
selection page

**Comment by desilinguist** [comment]
Yup, that's a good idea. Thanks for testing!

**Comment by desilinguist** [comment]
Partially addressed. Included authors but not abstracts.
