### ISSUE TITLE
Tutorials - Sort by time

### ISSUE THREAD

**Issue by dterg** [acl2017/acl2017.github.io#49]
## Environment information

- **Platform:** Mac
- **Operating system (incl. full version):** macOS Sierra (10.12.4)
- **Browser (incl. version):** Google Chrome v. 57.0.2987.133

---

## Expected behavior

Selecting tutorials in any order will give a list of the chosen tutorials sorted by time rather than order of selection. At the moment tutorials are assigned T1-T6, would be helpful to include the actual time in the final output (once timings are established) and sort the tutorials selected by the time rather the order of user selection.

## Steps to reproduce the erroneous behavior

Selecting all the tutorials in the morning or afternoon sessions in random order (e.g. T3, T1, T2) will give the same order in the output rather than sorting them by time (T1, T2, T3; assuming at this stage T1, T2, T3 will be in the same order time-wise).

**Comment by desilinguist** [comment]
Note that the three morning tutorials are parallel - all with the same starting and ending time as listed. And that's what the PDF shows. But good point about the sorting order, I will fix that.

**Comment by desilinguist** [comment]
Fixed.
