### ISSUE TITLE
WiNLP workshop 

### ISSUE THREAD

**Issue by LibbyBarak** [acl2017/acl2017.github.io#53]
The program is missing the WiNLP workshop altogether. It should be on July 30. I can see other workshops are not listed yet either. But, since this should be on the same day as the tutorials, it's a bit confusing.

Thanks,

Libby

---

## Environment information

- **Platform:** 
- **Operating system (incl. full version):** 
- **Browser (incl. version):** 

---

**Comment by desilinguist** [comment]
Hi Libby,

Like previous years, co-located events and workshops are not part of the
program page - it lists no workshops. Please see the workshops page on the
website for those events.

**Comment by callison-burch** [comment]
How hard would it be to add the workshops into your program viewer, Nitin?

**Comment by LibbyBarak** [comment]
The workshop page only has links to the individual websites. We've been
receiving emails from sponsors and mentors regarding the details for the
workshop: room for the workshop, the location of the poster session, and
location for lunch-mentoring event. I can't find this information anywhere
though it should be available somewhere, in a place that will be fairly
intuitive for people to figure out.

**Comment by callison-burch** [comment]
Hi Libby,

Here’s a copy of the printed handbook that has that info:  https://github.com/cfedermann/acl17-handbook/blob/master/final-build-no-meta-conf/handbook.pdf

—CCB

**Comment by desilinguist** [comment]
I am reluctant to add the workshops into the program since that would add a lot of scrolling to an already quite scroll-heavy page. I think I can just add the locations of the individual workshops on the "Workshops" page.

Please also note that the "Schedule" section of the Conference App includes all of the workshops.

**Comment by desilinguist** [comment]
I have added the locations (and also short abstractions) to the "Workshops" page on the website. Please take a look @LibbyBarak @callison-burch

**Comment by LibbyBarak** [comment]
Thanks.  Looks great.

**Comment by desilinguist** [comment]
👍🏼
