### ISSUE TITLE
Social Event Timing 7:00 or 7:30pm?

### ISSUE THREAD

**Issue by knmnyn** [acl2017/acl2017.github.io#54]
There are some inconsistencies with the social event program in the handbook and in the website as reported by Bonnie Webber to me.

Some pages (the printed handbook, pg 71 and http://acl2017.org/program) say 17:45-19:40 (poster) and 19:00-22:00 (social)
but others (the guidebook and http://acl2017.org/participants/#social-event ) say 17:45-19:45 (poster) and 19:30-22:30 (social) 
and yet another (pg 113 in the handbook) give 18:00-21:00 (social).  

We need to fix these confusions and check for any similar in the Wednesday sessions.

Also broadcasting in email.

- Min

---

## Environment information

- **Platform:** 
- **Operating system (incl. full version):** 
- **Browser (incl. version):** 

---

**Comment by desilinguist** [comment]
I have fixed the website to match the app when it comes to the social event
(7:30-10:30). The poster sessions already match (5:45-7:45) so there's no
inconsistency there.

I can't do anything about the handbook though.

**Comment by desilinguist** [comment]
I believe 7:30 is the correct time since Charley told me that's what the ticket says.
